"""add_behavioral_snapshots

Revision ID: 0066990f311e
Revises: 001_initial
Create Date: 2026-05-20 19:50:51.634419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0066990f311e'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_task_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_work_items_user_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_workspace_id'), table_name='work_items')
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False)
    op.create_index(op.f('ix_work_items_workspace_id'), 'work_items', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_work_items_user_id'), 'work_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_task_id'), 'sessions', ['task_id'], unique=False)
    # ### end Alembic commands ###
